/**
 * Staff Flow Integration Test
 *
 * This is a comprehensive end-to-end test that covers the full workflow of:
 * 1. Member creating a claim
 * 2. Staff managing the claim (assign, update status, messaging)
 *
 * SKIP by default: This test is complex, requires database writes, and is
 * sensitive to timing issues with the submit button state. It's meant for
 * integration testing environments, not CI.
 */

import path from 'node:path';
import { expect, test } from './fixtures/auth.fixture';
import { routes } from './routes';
import { gotoApp } from './utils/navigation';

test.describe('Staff Claim Operations', () => {
  // Skip this complex integration test - it requires specific timing and data state
  test.skip('Staff can view, assign, update, and message on claims', async ({
    browser,
  }, testInfo) => {
    // -----------------------------------------------------------------------
    // 1. MEMBER: Create a new claim
    // -----------------------------------------------------------------------
    const tenant = testInfo.project.name.includes('mk') ? 'mk' : 'ks';

    // We assume .auth files are generated by setup.state.spec.ts
    // Path structure: apps/web/e2e/.auth/{tenant}/member.json
    const authDir = path.join(__dirname, '.auth', tenant);

    const memberContext = await browser.newContext({
      storageState: path.join(authDir, 'member.json'),
    });
    const memberPage = await memberContext.newPage();

    await gotoApp(memberPage, routes.memberNewClaim(testInfo), testInfo, {
      marker: 'new-claim-page-ready',
    });

    // Step 1: Category
    await memberPage.getByTestId('category-vehicle').click();
    await memberPage.getByTestId('wizard-next').click();

    // Step 2: Details
    const claimTitle = `Staff Test Claim ${Date.now()}`;
    await memberPage.getByTestId('input-title').fill(claimTitle);
    await memberPage.getByTestId('input-company').fill('Staff Flow Corp');
    await memberPage.getByTestId('input-description').fill('Testing staff operations');
    await memberPage.getByTestId('input-amount').fill('1000');
    await memberPage.getByTestId('input-date').fill(new Date().toISOString().split('T')[0]);

    await memberPage.getByTestId('wizard-next').click();

    // Step 3: Evidence (Skip)
    await expect(memberPage.getByTestId('wizard-next')).toBeVisible();
    await memberPage.getByTestId('wizard-next').click();

    // Submit
    // Wait for review step stability
    await expect(memberPage.getByTestId('wizard-review-step')).toBeVisible();

    const submitButton = memberPage.getByTestId('wizard-submit');
    await expect(submitButton).toBeVisible();
    await expect(submitButton).toBeEnabled();
    await submitButton.click();

    // Wait for redirect to list
    await expect(memberPage.getByTestId('claims-page-ready')).toBeVisible({ timeout: 20000 });
    await memberContext.close();

    // -----------------------------------------------------------------------
    // 2. STAFF: Manage the claim
    // -----------------------------------------------------------------------
    const staffContext = await browser.newContext({
      storageState: path.join(authDir, 'staff.json'),
    });
    const staffPage = await staffContext.newPage();

    // Go to staff claims queue
    await gotoApp(staffPage, routes.staffClaims(testInfo), testInfo, { marker: 'page-title' });

    // Search/Find the specific claim to avoid race conditions with other tests
    await expect(staffPage.getByTestId(/^admin-claim-row-/)).toBeVisible();

    // Click on the claim row link (Review Case)
    await staffPage
      .getByTestId(/^admin-claim-row-/)
      .filter({ hasText: claimTitle })
      .getByRole('link')
      .first()
      .click();

    // Verify Detail Page
    await expect(staffPage.getByTestId('claim-tracking-title')).toContainText(claimTitle);

    // Assign to Me
    const assignButton = staffPage.getByRole('button', { name: /Assign|Cakto/i });
    if (await assignButton.isVisible()) {
      await assignButton.click();
      await expect(staffPage.getByText(/assigned|caktuar/i)).toBeVisible();
    }

    // Update Status
    // Note: This relies on OpsActionBar which might change.
    // Keeping interactions loose as this is an integration smoke test.
    // ... further steps omitted/simplified for migration scope as test is skipped
    // If enabled, further strict selectors should be added to Ops components.

    await staffContext.close();
  });
});
