import type { HelpNowCountry } from './content-packs';

export type HelpNowCopy = {
  timeLocale: string;
  title: string;
  subtitle: string;
  offline: string;
  emergency: string;
  continueSafe: string;
  countryLabel: string;
  countries: Readonly<Record<HelpNowCountry, string>>;
  darkTitle: string;
  darkBody: string;
  signedTitle: string;
  signedBody: string;
  evidenceTitle: string;
  privacy: string;
  noFile: string;
  localCountLabel: string;
  localCountNote: string;
  clear: string;
  tripTitle: string;
  download: string;
  downloadDone: string;
  downloadFailed: string;
  downloadUnsupported: string;
  packTitle: string;
  packBody: string;
  metricGuidance: string;
  guidanceFree: string;
  metricChecklist: string;
  metricFiles: string;
  generate: string;
  previewReady: string;
  continueLink: string;
  continueNote: string;
  scenarios: readonly string[];
  checklist: readonly string[];
  shots: readonly string[];
  tripChecklist: readonly string[];
};
