import type { HelpNowCopy } from './copy-types';

export const helpNowCopyEn: HelpNowCopy = {
  timeLocale: 'en',
  title: 'What happened?',
  subtitle: 'Roadside help that works before account creation.',
  offline:
    'Public guidance can be saved offline. Notes about your photos stay on this device and are never uploaded.',
  emergency: 'Someone is hurt: call local emergency services.',
  continueSafe: 'No one is hurt: continue the scene checklist.',
  countryLabel: 'Trip country',
  countries: {
    XK: 'Kosovo',
    MK: 'North Macedonia',
    AL: 'Albania',
    DE: 'Germany',
    AT: 'Austria',
    HU: 'Hungary',
    RS: 'Serbia',
    HR: 'Croatia',
    ME: 'Montenegro',
  },
  darkTitle: 'Country guidance not available yet',
  darkBody: 'Country-specific numbers and police rules are not shown for this country yet.',
  signedTitle: 'Country guidance available',
  signedBody: 'Public preview is available for this country. It still creates no case or account.',
  evidenceTitle: 'Photo guide',
  privacy:
    'Only basic details of the photos you pick (such as name, size and time) are noted on this device; originals are not uploaded and stay under your control.',
  noFile: 'No file selected',
  localCountLabel: 'Photos noted on this device',
  localCountNote: 'nothing sent',
  clear: 'Clear photo notes on this device',
  tripTitle: 'Trip Mode',
  download: 'Download public Trip Mode pack',
  downloadDone: 'Public pack saved for offline use.',
  downloadFailed: 'Offline save failed. Try again before you travel.',
  downloadUnsupported: 'Offline save is not supported in this browser.',
  packTitle: 'Free incident pack preview',
  packBody: 'Checklist, photo prompts and next-step options only. No case is created here.',
  metricGuidance: 'Guidance',
  guidanceFree: 'Free and public',
  metricChecklist: 'Checklist steps done',
  metricFiles: 'Photos noted',
  generate: 'Generate local preview',
  previewReady: 'Local preview ready on this device',
  continueLink: 'Organize incident details',
  continueNote:
    'The free organizer on the home page starts separately. Opening it sends nothing from this page: your checklist, photo notes and country stay here, and no claim, account or contact request is created. You choose what to enter there.',
  scenarios: ['Car accident', 'Injury', 'Property damage', 'Flight: coming soon'],
  checklist: [
    'Move to safety',
    'Turn on hazard lights',
    'Take scene photos',
    'Exchange details',
    'Find witnesses',
    'Do not admit fault',
  ],
  shots: [
    'Wide scene',
    'Number plates',
    'Damage close-up',
    'Road context',
    'Documents',
    'Witness notes',
  ],
  tripChecklist: [
    'Green Card',
    'European accident statement',
    'Vehicle documents',
    'Family contact',
    'Offline pack',
  ],
};
