import type { HelpNowCopy } from './copy-types';

export const helpNowCopySq: HelpNowCopy = {
  timeLocale: 'sq',
  title: 'Çfarë ndodhi?',
  subtitle: 'Ndihmë në rrugë para hapjes së llogarisë.',
  offline:
    'Udhëzimet publike mund të ruhen për përdorim pa internet. Shënimet për fotot mbeten në këtë pajisje dhe nuk ngarkohen kurrë.',
  emergency: 'Nëse ka të lënduar, thirrni urgjencën lokale.',
  continueSafe: 'Nëse nuk ka të lënduar, vazhdoni listën e vendit të ngjarjes.',
  countryLabel: 'Shteti i udhëtimit',
  countries: {
    XK: 'Kosova',
    MK: 'Maqedonia e Veriut',
    AL: 'Shqipëria',
    DE: 'Gjermania',
    AT: 'Austria',
    HU: 'Hungaria',
    RS: 'Serbia',
    HR: 'Kroacia',
    ME: 'Mali i Zi',
  },
  darkTitle: 'Udhëzimet për këtë vend nuk janë ende të disponueshme',
  darkBody: 'Numrat dhe rregullat e policisë për këtë vend nuk shfaqen ende.',
  signedTitle: 'Udhëzimet për vendin janë të disponueshme',
  signedBody: 'Parapamja publike është e hapur për këtë vend. Ende nuk hap rast ose llogari.',
  evidenceTitle: 'Udhëzuesi për fotot',
  privacy:
    'Në këtë pajisje shënohen vetëm të dhënat bazë të fotove që zgjidhni (si emri, madhësia dhe koha); origjinalet nuk ngarkohen dhe mbeten nën kontrollin tuaj.',
  noFile: 'Asnjë skedar i zgjedhur',
  localCountLabel: 'Foto të shënuara në këtë pajisje',
  localCountNote: 'asgjë nuk dërgohet',
  clear: 'Fshi shënimet e fotove në këtë pajisje',
  tripTitle: 'Modaliteti i udhëtimit',
  download: 'Shkarko paketën publike të udhëtimit',
  downloadDone: 'Paketa publike u ruajt për përdorim pa internet.',
  downloadFailed: 'Ruajtja pa internet dështoi. Provoni përsëri para udhëtimit.',
  downloadUnsupported: 'Ruajtja pa internet nuk mbështetet në këtë shfletues.',
  packTitle: 'Parapamje falas e paketës së ngjarjes',
  packBody:
    'Vetëm lista, udhëzime për foto dhe mundësi për hapin e ardhshëm. Këtu nuk hapet asnjë rast.',
  metricGuidance: 'Udhëzimet',
  guidanceFree: 'Falas dhe publike',
  metricChecklist: 'Hapa të kryer',
  metricFiles: 'Foto të shënuara',
  generate: 'Krijo parapamjen lokale',
  previewReady: 'Parapamja lokale është gati në këtë pajisje',
  continueLink: 'Organizo të dhënat e ngjarjes',
  continueNote:
    'Organizuesi falas në faqen kryesore fillon veçmas. Hapja e tij nuk dërgon asgjë nga kjo faqe: lista, shënimet e fotove dhe shteti mbeten këtu, dhe nuk krijohet asnjë kërkesë, llogari apo kontakt. Ju zgjidhni çfarë të shkruani atje.',
  scenarios: ['Aksident me veturë', 'Lëndim', 'Dëm prone', 'Fluturim: së shpejti'],
  checklist: [
    'Dilni në vend të sigurt',
    'Ndizni dritat paralajmëruese',
    'Bëni foto',
    'Shkëmbeni të dhënat',
    'Gjeni dëshmitarë',
    'Mos pranoni fajin',
  ],
  shots: [
    'Pamje e gjerë e vendit',
    'Targat',
    'Dëmi nga afër',
    'Rruga përreth',
    'Dokumentet',
    'Shënime për dëshmitarët',
  ],
  tripChecklist: [
    'Karta e Gjelbër',
    'Deklarata evropiane e aksidentit',
    'Dokumentet e automjetit',
    'Kontakti i familjes',
    'Paketa pa internet',
  ],
};
